/******************************************************************************/
/***          Generated by IBExpert 2009.03.23 06.12.2010 15:46:07          ***/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1251;


SET TERM ^ ; 



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/

CREATE PROCEDURE PS_NOMENS_LIBRA (
    IADD_PURE_REST INTEGER,
    ILIBRA_NUM VARCHAR(7))
RETURNS (
    ONOMEN_ID INTEGER,
    OOUT_PRICE DOUBLE PRECISION,
    ONOMEN_CODE INTEGER,
    ONOMEN_NAME VARCHAR(40),
    ODATE DATE,
    OREST DOUBLE PRECISION)
AS
BEGIN
  SUSPEND;
END^



SET TERM ; ^



/******************************************************************************/
/***                           Stored Procedures                            ***/
/******************************************************************************/


SET TERM ^ ;

ALTER PROCEDURE PS_NOMENS_LIBRA (
    IADD_PURE_REST INTEGER,
    ILIBRA_NUM VARCHAR(7))
RETURNS (
    ONOMEN_ID INTEGER,
    OOUT_PRICE DOUBLE PRECISION,
    ONOMEN_CODE INTEGER,
    ONOMEN_NAME VARCHAR(40),
    ODATE DATE,
    OREST DOUBLE PRECISION)
AS
begin
  ilibra_num = :ilibra_num || '%';
  for select n.nomen_id, n.nomen_code, n.nomen_name, around(n.out_price) from nomen n
      where n.nomen_code like :ilibra_num
    into onomen_id,  onomen_code, onomen_name, oout_price
  do begin
    select max(g.doc_date) + 30, sum(g.goods_rest) from goods g
        where g.nomen_id = :onomen_id
      into odate, orest;

    if (:odate is null) then odate = cast ('today' as date) + 30;

    if ((:iadd_pure_rest <> 0) or ((:iadd_pure_rest = 0) and
         (((:orest < -0.001) or (:orest > 0.001))))) then
        suspend;
    orest = NULL;
    odate = NULL;
  end
end^



SET TERM ; ^
