/******************************************************************************/
/***          Generated by IBExpert 2009.03.23 22.11.2011 18:57:13          ***/
/******************************************************************************/



SET SQL DIALECT 3;

SET NAMES WIN1251;

/* заповнюється таблиця з режимами функціонування ТП    */
INSERT INTO TS_TP_MODES (TP_MODE_ID, NAME) VALUES (0, 'Аварійний');
INSERT INTO TS_TP_MODES (TP_MODE_ID, NAME) VALUES (1, 'Звичайний');
INSERT INTO TS_TP_MODES (TP_MODE_ID, NAME) VALUES (2, 'Відновлення');

COMMIT WORK;

/* в таблицю поточного стану встановлюється єдиний запис з режимом синхронізації */
INSERT INTO T_TP_STATES (TP_MODE_ID) VALUES (1);

COMMIT WORK;

